import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices, type PartialLangiumSharedServices } from 'langium/lsp';
import { OmlGeneratedModule, OmlGeneratedSharedModule } from './generated/module.js';
import { OmlValidator, registerValidationChecks } from './oml-validator.js';
import { OmlValueConverter } from './oml-converter.js';
import { OmlScopeProvider } from './oml-scope.js';
import { OmlCompletionProvider } from './oml-completion.js';
import { OmlHoverProvider } from './oml-hover.js';
import { OmlNodeKindProvider } from './oml-node-kind-provider.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type OmlAddedServices = {
    validation: {
        OmlValidator: OmlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type OmlServices = LangiumServices & OmlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const OmlModule: Module<OmlServices, PartialLangiumServices & OmlAddedServices> = {
    validation: {
        OmlValidator: () => new OmlValidator()
    },
    parser: {
        ValueConverter: () => new OmlValueConverter()
    },
    references: {
        ScopeProvider: (services: any) => new OmlScopeProvider(services)
    },
    lsp: {
        CompletionProvider: (services: any) => new OmlCompletionProvider(services),
        HoverProvider: (services: any) => new OmlHoverProvider(services)
    }
};

/**
 * Shared module that overrides default shared services.
 * NodeKindProvider is a shared service used by DocumentSymbolProvider and WorkspaceSymbolProvider.
 */
export const OmlSharedModule: Module<LangiumSharedServices, PartialLangiumSharedServices> = {
    lsp: {
        NodeKindProvider: () => new OmlNodeKindProvider()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createOmlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Oml: OmlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        OmlGeneratedSharedModule,
        OmlSharedModule
    );
    const Oml = inject(
        createDefaultModule({ shared }),
        OmlGeneratedModule,
        OmlModule
    );
    shared.ServiceRegistry.register(Oml);
    registerValidationChecks(Oml);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Oml };
}
